name: 转换Clash规则为Surge格式

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：下载存放 YAML 文件的 clash_rules 仓库
      - name: 检出 clash_rules 仓库 (源)
        uses: actions/checkout@v3
        with:
          repository: xiongking/clash_rules

      # 步骤2：下载并准备 subconverter
      - name: 下载并准备 subconverter
        run: |
          wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
          tar -xvf subconverter_linux64.tar.gz
          chmod +x subconverter/subconverter

      # 步骤3：批量转换所有YAML规则
      - name: 批量转换所有YAML规则
        run: |
          mkdir -p surge_rules_repo
          find . -type f -name "*.yaml" | while read -r file; do
            filename=$(basename "$file" .yaml)
            echo "✅ 正在转换: '$file' -> 'surge_rules_repo/${filename}.list'"
            # 【核心修正】直接将输出重定向到目标文件夹，这是最直接可靠的方式
            ./subconverter/subconverter -g -i "$file" -t surge > surge_rules_repo/${filename}.list
          done

      # 步骤4：检出目标仓库的 .git 历史记录（仅用于提交）
      - name: 检出 surge_rules 仓库 (目标)
        uses: actions/checkout@v3
        with:
          repository: xiongking/surge_rules 
          path: surge_rules_repo
          token: ${{ secrets.ACCESS_TOKEN }}

      # 步骤5：提交并推送更改
      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: surge_rules_repo
          commit_message: "chore(auto): 定期自动更新 Surge 规则"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
