name: 转换Clash分流规则为Surge格式 (极简可靠版)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：下载存放 YAML 规则的 clash_rules 仓库
      - name: 检出 clash_rules 仓库 (源)
        uses: actions/checkout@v3
        with:
          repository: xiongking/clash_rules

      # 步骤2：批量转换所有YAML规则 (使用 sed 命令)
      - name: 批量转换所有YAML规则
        run: |
          mkdir surge_output
          find . -type f -name "*.yaml" | while read -r file; do
            filename=$(basename "$file" .yaml)
            echo "✅ 正在转换: '$file' -> 'surge_output/${filename}.list'"
            
            # 【核心修正】使用 sed 命令，直接从YAML中提取和清理规则
            # 1. 从 "payload:" 那一行开始读取文件
            # 2. 删除第一行 (即 "payload:" 本身)
            # 3. 删除每一行行首的 "- " (包括空格)
            # 4. 删除所有的单引号 "'"
            # 5. 将结果保存到新文件中
            sed -n '/payload:/,$p' "$file" | sed '1d' | sed 's/^[ ]*- //g' | sed "s/'//g" > "surge_output/${filename}.list"
          done
          
          echo "--- 转换完成，检查输出目录内容 ---"
          ls -la surge_output

      # 步骤3：检出用于存放结果的 surge_rules 仓库
      - name: 检出 surge_rules 仓库 (目标)
        uses: actions/checkout@v3
        with:
          repository: xiongking/surge_rules 
          path: surge_rules_repo
          token: ${{ secrets.ACCESS_TOKEN }}

      # 步骤4：将转换好的新规则文件，复制到目标仓库中
      - name: 复制新规则文件
        run: |
          cp -rf surge_output/. surge_rules_repo/

      # 步骤5：自动提交并推送到 surge_rules 仓库
      - name: 提交并推送更改
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: surge_rules_repo
          commit_message: "chore(auto): 定期更新 Surge 分流规则"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
